# Generated by Django 4.0.4 on 2022-04-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='External',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='Адрес')),
                ('domain', models.CharField(max_length=100, verbose_name='Домен')),
                ('create_data', models.DateTimeField(verbose_name='Дата создания')),
                ('update_data', models.DateTimeField(verbose_name='Дата обновления')),
                ('country', models.CharField(max_length=10, null=True, verbose_name='Страна')),
                ('is_dead', models.BooleanField(verbose_name='Работает ли')),
                ('a', models.CharField(max_length=150, null=True, verbose_name='Включена ли запись "А')),
                ('ns', models.CharField(max_length=150, null=True, verbose_name='Включена ли запись "NS')),
                ('cname', models.CharField(max_length=150, null=True, verbose_name='Включена ли запись "CNAME"')),
                ('mx', models.CharField(max_length=150, null=True, verbose_name='Включена ли запись "MX"')),
                ('txt', models.CharField(max_length=150, null=True, verbose_name='Включена ли запись "TXT"')),
            ],
            options={
                'verbose_name': 'Данные парсинга',
                'verbose_name_plural': 'Данные парсинга',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_object', models.CharField(max_length=100, verbose_name='Поиск запрошенного в БД:')),
            ],
        ),
    ]
