# Generated by Django 4.0.4 on 2022-04-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='External',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, verbose_name='Адрес')),
                ('domains', models.CharField(max_length=30, verbose_name='Домен')),
                ('create_data', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('update_data', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('contry', models.CharField(max_length=20, verbose_name='Страна')),
                ('is_dead', models.CharField(max_length=30, verbose_name='Хз что это')),
                ('a', models.CharField(max_length=30, verbose_name='')),
                ('ns', models.CharField(max_length=30, verbose_name='')),
                ('cname', models.CharField(max_length=30, verbose_name='')),
                ('mx', models.CharField(max_length=30, verbose_name='')),
                ('txt', models.CharField(max_length=30, verbose_name='')),
            ],
            options={
                'verbose_name': 'Данные парсинга',
                'verbose_name_plural': 'Данные парсинга',
            },
        ),
    ]
