# Generated by Django 4.0.4 on 2022-04-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_result_create_data_alter_result_update_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_object', models.TextField(max_length=100, verbose_name='Поиск запрошенного в БД.')),
            ],
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
